package com.theultimatejavaseries.advanced.exceptions;

public class Main {
    public static void main(String[] args) {
        // ExceptionsDemo.show();
        // ExceptionsDemo.catchingExceptions();

        // try {
        // ExceptionsDemo.throwingExceptions();
        // } catch (Throwable e) {
        // // throwable used to catch all possible exceptions
        // System.out.println("An unexpected error occurred.");
        // }

        ExceptionsDemo.customExceptions();
    }
}
